# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac6eff7766fee279c7c4c29c7b0a08626156215aafe86931d5aac89b2078396b82e6df92c8aef19e137e3a5dc83c46971a5f3edc29a1488344fd70bdb2ba6ad5

test:
  secret_key_base: 2c14dae325c5694795e937633be7e422d7bc6b7b69639019941c69bfc3806975ec5999e4d9d3da972315df2730af2078b7c9d1eea8bc6f1fbcdad2a5671d7d91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
